//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no piece in the chosen coordinates.
        /// </summary>
        internal static string CoordinateNotValid {
            get {
                return ResourceManager.GetString("CoordinateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the destination coordinates: .
        /// </summary>
        internal static string DestinationCoordinates {
            get {
                return ResourceManager.GetString("DestinationCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error choosing the Column, enter a column again.
        /// </summary>
        internal static string ErrorColumn {
            get {
                return ResourceManager.GetString("ErrorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen value is not numeric, choose a column again.
        /// </summary>
        internal static string ErrorConvertionNumeric {
            get {
                return ResourceManager.GetString("ErrorConvertionNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error choosing the Row, enter another one again.
        /// </summary>
        internal static string ErrorRow {
            get {
                return ResourceManager.GetString("ErrorRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interposed piece.
        /// </summary>
        internal static string InterposedPiece {
            get {
                return ResourceManager.GetString("InterposedPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not a valid move for this piece..
        /// </summary>
        internal static string InvalidMovement {
            get {
                return ResourceManager.GetString("InvalidMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to select a Random play?.
        /// </summary>
        internal static string RandomPlay {
            get {
                return ResourceManager.GetString("RandomPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a column.
        /// </summary>
        internal static string ReadColumn {
            get {
                return ResourceManager.GetString("ReadColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a row.
        /// </summary>
        internal static string ReadRow {
            get {
                return ResourceManager.GetString("ReadRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the selected coordinate, there is a piueza of the same color.
        /// </summary>
        internal static string SameColor {
            get {
                return ResourceManager.GetString("SameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected piece is:.
        /// </summary>
        internal static string SelectedPiece {
            get {
                return ResourceManager.GetString("SelectedPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to continue?.
        /// </summary>
        internal static string WantToContinue {
            get {
                return ResourceManager.GetString("WantToContinue", resourceCulture);
            }
        }
    }
}
